export interface TechItem {
  name: string;
  icon: string;
}

export interface Project {
  id: string;
  title: string;
  url: string;
  description: string;
  features: string[];
  tech: TechItem[];
  gradient: string;
  accent: {
    dash: string;
    fill: string;
    text: string;
    bg: string;
  };
  images: {
    mobile1: string;
    mobile2: string;
    main: string;
  };
  mainImageFit?: "cover" | "fill";
}

const tech = {
  react: { name: "React", icon: "/icons/React_dark.svg" },
  typescript: { name: "TypeScript", icon: "/icons/typescript.svg" },
  nextjs: { name: "Next.js", icon: "/icons/nextjs_icon_dark.svg" },
  tailwind: { name: "Tailwind CSS", icon: "/icons/tailwindcss.svg" },
  runeai: { name: "RuneAI", icon: "/icons/RuneLogo.svg" },
  framer: { name: "Framer Motion", icon: "/icons/Motion_dark.svg" },
  prism: { name: "Prism.js", icon: "/icons/RuneLogo.svg" },
  vercel: { name: "Vercel", icon: "/icons/Vercel_dark.svg" },
  langgraph: { name: "LangGraph", icon: "/icons/langgraph.svg" },
  tavily: { name: "Tavily", icon: "/icons/tavily.svg" },
  appwrite: { name: "Appwrite", icon: "/icons/appwrite.svg" },
  nodejs: { name: "Node.js", icon: "/icons/nodejs.svg" },
  gsap: { name: "GSAP", icon: "/icons/gsap.svg" },
  prisma: { name: "Prisma", icon: "/icons/Prisma_dark.svg" },
};

export const projects: Project[] = [
  {
    id: "rune",
    title: "Rune",
    url: "https://rune.codes",
    description:
      "🚀 Rune is your all-in-one productivity toolkit featuring 145+ powerful tools for learning, creating, and working smarter. From text & writing tools, PDF management, image editing, video processing, to developer utilities, calculators, and AI-powered assistants—Rune empowers students, professionals, and creators with free 24/7 access to streamline their workflow.",
    features: [
      "145+ free tools including text editors, PDF converters, and image processors",
      "AI-powered tools for writing, summarizing, and content creation",
      "Developer utilities with JSON formatter, regex tester, and code tools",
    ],
    tech: [
      tech.react,
      tech.typescript,
      tech.nextjs,
      tech.tailwind,
      tech.runeai,
      tech.framer,
    ],
    gradient:
      "linear-gradient(10deg, rgb(153, 27, 27) 49.9%, rgb(153, 27, 27) 81.7%, rgb(239, 68, 68) 99.88%, rgb(249, 215, 147) 113.5%)",
    accent: {
      dash: "bg-red-600",
      fill: "fill-red-600",
      text: "text-red-400",
      bg: "bg-red-600/20",
    },
    images: {
      mobile1: "/images/projects/rune-mobile-1.png",
      mobile2: "/images/projects/rune-mobile-2.png",
      main: "/images/projects/rune-main.png",
    },
  },
  {
    id: "runehub",
    title: "RuneHub",
    url: "https://rune.codes/hub",
    description:
      "🚀 RuneHub is a comprehensive programming education platform featuring extensive tutorials and articles on different programming languages, frameworks, and technologies. It includes a dedicated tech trends section with the latest industry news and insights, now powered by its own powerful custom CMS.",
    features: [
      "62+ topics to study across different programming languages and technologies",
      "RuneAI powered key insights for accelerated learning",
      "Developer focused UX with its own powerful custom CMS",
    ],
    tech: [
      tech.react,
      tech.typescript,
      tech.nextjs,
      tech.tailwind,
      tech.runeai,
      tech.prism,
    ],
    gradient:
      "linear-gradient(10deg, rgb(41, 50, 203) 49.9%, rgb(41, 50, 203) 81.7%, rgb(121, 128, 255) 99.88%, rgb(249, 215, 147) 113.5%)",
    accent: {
      dash: "bg-blue-600",
      fill: "fill-blue-600",
      text: "text-blue-400",
      bg: "bg-blue-600/20",
    },
    images: {
      mobile1: "/images/projects/runehub-mobile-1.png",
      mobile2: "/images/projects/runehub-mobile-2.png",
      main: "/images/projects/runehub-main.png",
    },
  },
  {
    id: "runelearn",
    title: "RuneLearn",
    url: "https://rune.codes/learn",
    description:
      "🚀 RuneLearn is an ultimate AI-powered study companion that dynamically generates quizzes, intelligent flashcards, personalized roadmaps, and instantly resolves doubts with its deep-context advanced doubt solver. Designed to turbocharge long-term memory and retention effortlessly.",
    features: [
      "Interactive Quizzes and Flashcards dynamically generated by AI",
      "Personalized Learning Roadmaps tailored to your study goals",
      "Advanced Doubt Solver providing in-depth explanations instantly",
    ],
    tech: [
      tech.react,
      tech.typescript,
      tech.nextjs,
      tech.tailwind,
      tech.runeai,
      tech.vercel,
    ],
    gradient:
      "linear-gradient(10deg, rgb(120, 53, 15) 49.9%, rgb(146, 64, 14) 81.7%, rgb(180, 83, 9) 99.88%, rgb(249, 215, 147) 113.5%)",
    accent: {
      dash: "bg-amber-700",
      fill: "fill-amber-700",
      text: "text-amber-400",
      bg: "bg-amber-700/20",
    },
    images: {
      mobile1: "/images/projects/runelearn-mobile-1.png",
      mobile2: "/images/projects/runelearn-mobile-2.png",
      main: "/images/projects/runelearn-main.png",
    },
  },
  {
    id: "runecareer",
    title: "RuneCareer",
    url: "https://rune.codes/career",
    description:
      "🚀 RuneCareer is a complete career suite with a resume builder, LaTeX editor, ATS checker, and AI-guided cover and resignation letters. Pro templates and Rune AI suggestions help you ship polished applications fast.",
    features: [
      "Resume builder with pro templates and one-click formatting",
      "LaTeX editor with live preview for academic CVs",
      "ATS checker plus AI-assisted cover and resignation letters",
    ],
    tech: [
      tech.react,
      tech.typescript,
      tech.nextjs,
      tech.tailwind,
      tech.runeai,
      tech.framer,
    ],
    gradient:
      "linear-gradient(10deg, rgb(136, 19, 55) 49.9%, rgb(136, 19, 55) 81.7%, rgb(190, 24, 93) 99.88%, rgb(251, 207, 232) 113.5%)",
    accent: {
      dash: "bg-red-600",
      fill: "fill-red-600",
      text: "text-red-400",
      bg: "bg-red-600/20",
    },
    images: {
      mobile1: "/images/projects/runecareer-mobile-1.png",
      mobile2: "/images/projects/runecareer-mobile-2.png",
      main: "/images/projects/runecareer-main.png",
    },
  },
  {
    id: "runeai",
    title: "RuneAI",
    url: "https://ai.rune.codes",
    description:
      "🚀 Rune AI featuring a powerful RAG system, three specialized models (Fast, Thinking, Pro), and a massive 500K context limit. Includes advanced Web Search capable of deep research and intelligent Tool Calling automation.",
    features: [
      "Powered by its own dedicated server for AI models hosted on Digital Ocean",
      "Massive 500K context limit for deep document analysis",
      "Advanced Web Search and intelligent automated Tool Calling",
    ],
    tech: [
      tech.runeai,
      tech.langgraph,
      tech.tavily,
      tech.appwrite,
      tech.nextjs,
      tech.vercel,
    ],
    gradient:
      "linear-gradient(12deg, rgb(63, 63, 70) 49.9%, rgb(113, 113, 122) 81.7%, rgb(212, 212, 216) 99.88%, rgb(250, 250, 250) 113.5%)",
    accent: {
      dash: "bg-orange-600",
      fill: "fill-orange-600",
      text: "text-orange-400",
      bg: "bg-orange-600/20",
    },
    images: {
      mobile1: "/images/projects/runeai-mobile-1.png",
      mobile2: "/images/projects/runeai-mobile-2.png",
      main: "/images/projects/runeai-main.png",
    },
    mainImageFit: "fill",
  },
  {
    id: "old-portfolio",
    title: "Old Portfolio",
    url: "https://parthsharma.me",
    description:
      "🚀 A premium, high-performance portfolio crafted for the modern web. Featuring fluid GSAP animations, physics-based interactions, and a polished aesthetic, this template sets a new standard for creative developers. Built with a robust stack including Next.js, Prisma, and Zustand, it offers a seamless blend of design excellence and engineering precision.",
    features: [
      "Premium, high-performance design with fluid GSAP animations",
      "Physics-based interactions and advanced state management",
      "Robust full-stack architecture with Prisma and Node.js",
    ],
    tech: [
      tech.react,
      tech.typescript,
      tech.nextjs,
      tech.nodejs,
      tech.tailwind,
      tech.gsap,
    ],
    gradient:
      "linear-gradient(10deg, rgb(153, 27, 27) 49.9%, rgb(153, 27, 27) 81.7%, rgb(239, 68, 68) 99.88%, rgb(249, 215, 147) 113.5%)",
    accent: {
      dash: "bg-red-600",
      fill: "fill-red-600",
      text: "text-red-400",
      bg: "bg-red-600/20",
    },
    images: {
      mobile1: "/images/projects/portfolio-mobile-1.png",
      mobile2: "/images/projects/portfolio-mobile-2.png",
      main: "/images/projects/portfolio-main.png",
    },
  },
];
