/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as SignatureBookRouteImport } from './routes/signature-book'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OffTheClockRouteImport } from './routes/off-the-clock'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as CreativeRouteImport } from './routes/creative'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const SignatureBookRoute = SignatureBookRouteImport.update({
  id: '/signature-book',
  path: '/signature-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OffTheClockRoute = OffTheClockRouteImport.update({
  id: '/off-the-clock',
  path: '/off-the-clock',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeRoute = CreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/creative': typeof CreativeRoute
  '/guestbook': typeof GuestbookRoute
  '/off-the-clock': typeof OffTheClockRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/signature-book': typeof SignatureBookRoute
  '/uses': typeof UsesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/creative': typeof CreativeRoute
  '/guestbook': typeof GuestbookRoute
  '/off-the-clock': typeof OffTheClockRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/signature-book': typeof SignatureBookRoute
  '/uses': typeof UsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/creative': typeof CreativeRoute
  '/guestbook': typeof GuestbookRoute
  '/off-the-clock': typeof OffTheClockRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/signature-book': typeof SignatureBookRoute
  '/uses': typeof UsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/creative'
    | '/guestbook'
    | '/off-the-clock'
    | '/privacy'
    | '/projects'
    | '/signature-book'
    | '/uses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/creative'
    | '/guestbook'
    | '/off-the-clock'
    | '/privacy'
    | '/projects'
    | '/signature-book'
    | '/uses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/creative'
    | '/guestbook'
    | '/off-the-clock'
    | '/privacy'
    | '/projects'
    | '/signature-book'
    | '/uses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CreativeRoute: typeof CreativeRoute
  GuestbookRoute: typeof GuestbookRoute
  OffTheClockRoute: typeof OffTheClockRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  SignatureBookRoute: typeof SignatureBookRoute
  UsesRoute: typeof UsesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signature-book': {
      id: '/signature-book'
      path: '/signature-book'
      fullPath: '/signature-book'
      preLoaderRoute: typeof SignatureBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/off-the-clock': {
      id: '/off-the-clock'
      path: '/off-the-clock'
      fullPath: '/off-the-clock'
      preLoaderRoute: typeof OffTheClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative': {
      id: '/creative'
      path: '/creative'
      fullPath: '/creative'
      preLoaderRoute: typeof CreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CreativeRoute: CreativeRoute,
  GuestbookRoute: GuestbookRoute,
  OffTheClockRoute: OffTheClockRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  SignatureBookRoute: SignatureBookRoute,
  UsesRoute: UsesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
